#!/usr/bin/env python
import string


# The most efficient way of returning the most wanted letter in a given string.
def check_io(text):
    text = text.lower()
    return max(string.ascii_lowercase, key=text.count())


print(check_io("My name is venkata sai praneeth palakurthi"))
