#!/usr/bin/env python
import string


def check_io(text):
    text = text.lower()
    return max(string.ascii_lowercase, key=text.count())


print(check_io("My name is venkata sai praneeth palakurthi"))