#!/usr/bin/env python
from string import *


def check_io(text):
    op = []  # used to store the maximum number of times that a letter is occurred

    # Used for removing the numbers, white spaces, and punctuations in the string.
    text = "".join(x for x in text if x not in punctuation)
    text = "".join(x for x in text if not x.isdigit())
    text = sorted(text.replace(" ", "").lower())
    # If length of the text is 1 then just return the letter
    count = 1
    if len(text) == 1:
        return text[0]
    else:
        for i in range(0, len(text) - 1):
            if text[i] == text[i + 1]:
                count += 1
                op.append(count)
            else:
                op.append(1)
                count = 1
    # returning the index of the character that is repeated mostly
    index_char = op.index(max(op))
    return text[index_char]


print(check_io("My name is venkata sai praneeth palakurthi"))
